cp ./Activity/ScrImg_ActivityBg.png ScrImg_ActivityBg.png
cp ./Activity/ScrImg_ActivityBg@2x.png ScrImg_ActivityBg@2x.png
cp ./Activity/ScrImg_DefaultGreyBtnTall.png ScrImg_DefaultGreyBtnTall.png
cp ./Activity/ScrImg_DefaultGreyBtnTall@2x.png ScrImg_DefaultGreyBtnTall@2x.png
cp ./Activity/ScrImg_DefaultGreyBtnTallPressed.png ScrImg_DefaultGreyBtnTallPressed.png
cp ./Activity/ScrImg_DefaultGreyBtnTallPressed@2x.png ScrImg_DefaultGreyBtnTallPressed@2x.png
cp ./Activity/ScrImg_DropdownMenuBg.png ScrImg_DropdownMenuBg.png
cp ./Activity/ScrImg_DropdownMenuBg@2x.png ScrImg_DropdownMenuBg@2x.png
cp ./Activity/ScrImg_EmailShareBtn.png ScrImg_EmailShareBtn.png
cp ./Activity/ScrImg_EmailShareBtn@2x.png ScrImg_EmailShareBtn@2x.png
cp ./Activity/ScrImg_FacebookShareBtn.png ScrImg_FacebookShareBtn.png
cp ./Activity/ScrImg_FacebookShareBtn@2x.png ScrImg_FacebookShareBtn@2x.png
cp ./Activity/ScrImg_LikeOff.png ScrImg_LikeOff.png
cp ./Activity/ScrImg_LikeOff@2x.png ScrImg_LikeOff@2x.png
cp ./Activity/ScrImg_LikeOn.png ScrImg_LikeOn.png
cp ./Activity/ScrImg_LikeOn@2x.png ScrImg_LikeOn@2x.png
cp ./Activity/ScrImg_PlayBtn.png ScrImg_PlayBtn.png
cp ./Activity/ScrImg_PlayBtn@2x.png ScrImg_PlayBtn@2x.png
cp ./Activity/ScrImg_RedBtn.png ScrImg_RedBtn.png
cp ./Activity/ScrImg_RedBtn@2x.png ScrImg_RedBtn@2x.png
cp ./Activity/ScrImg_RedBtnPressed.png ScrImg_RedBtnPressed.png
cp ./Activity/ScrImg_RedBtnPressed@2x.png ScrImg_RedBtnPressed@2x.png
cp ./Activity/ScrImg_ShareIcon.png ScrImg_ShareIcon.png
cp ./Activity/ScrImg_ShareIcon@2x.png ScrImg_ShareIcon@2x.png
cp ./Activity/ScrImg_TwitterShareBtn.png ScrImg_TwitterShareBtn.png
cp ./Activity/ScrImg_TwitterShareBtn@2x.png ScrImg_TwitterShareBtn@2x.png
cp ./Dashboard-Main/ScrImg_ActivityIcon.png ScrImg_ActivityIcon.png
cp ./Dashboard-Main/ScrImg_ActivityIcon@2x.png ScrImg_ActivityIcon@2x.png
cp ./Dashboard-Main/ScrImg_AppsDealApp.png ScrImg_AppsDealApp.png
cp ./Dashboard-Main/ScrImg_AppsDealApp@2x.png ScrImg_AppsDealApp@2x.png
cp ./Dashboard-Main/ScrImg_AppsDealBg.png ScrImg_AppsDealBg.png
cp ./Dashboard-Main/ScrImg_AppsDealBg@2x.png ScrImg_AppsDealBg@2x.png
cp ./Dashboard-Main/ScrImg_AppsDealDash.png ScrImg_AppsDealDash.png
cp ./Dashboard-Main/ScrImg_AppsDealDash@2x.png ScrImg_AppsDealDash@2x.png
cp ./Dashboard-Main/ScrImg_AppsDealPriceTag.png ScrImg_AppsDealPriceTag.png
cp ./Dashboard-Main/ScrImg_AppsDealPriceTag@2x.png ScrImg_AppsDealPriceTag@2x.png
cp ./Dashboard-Main/ScrImg_AppsDealsIcon.png ScrImg_AppsDealsIcon.png
cp ./Dashboard-Main/ScrImg_AppsDealsIcon@2x.png ScrImg_AppsDealsIcon@2x.png
cp ./Dashboard-Main/ScrImg_AppsDealStarEmpty.png ScrImg_AppsDealStarEmpty.png
cp ./Dashboard-Main/ScrImg_AppsDealStarEmpty@2x.png ScrImg_AppsDealStarEmpty@2x.png
cp ./Dashboard-Main/ScrImg_AppsDealStarFull.png ScrImg_AppsDealStarFull.png
cp ./Dashboard-Main/ScrImg_AppsDealStarFull@2x.png ScrImg_AppsDealStarFull@2x.png
cp ./Dashboard-Main/ScrImg_Bg-568h@2x.png ScrImg_Bg-568h@2x.png
cp ./Dashboard-Main/ScrImg_Bg.png ScrImg_Bg.png
cp ./Dashboard-Main/ScrImg_Bg@2x.png ScrImg_Bg@2x.png
cp ./Dashboard-Main/ScrImg_CloseIcon.png ScrImg_CloseIcon.png
cp ./Dashboard-Main/ScrImg_CloseIcon@2x.png ScrImg_CloseIcon@2x.png
cp ./Dashboard-Main/ScrImg_DashbaordArrow.png ScrImg_DashbaordArrow.png
cp ./Dashboard-Main/ScrImg_DashbaordArrow@2x.png ScrImg_DashbaordArrow@2x.png
cp ./Dashboard-Main/ScrImg_DashboardBadge1.png ScrImg_DashboardBadge1.png
cp ./Dashboard-Main/ScrImg_DashboardBadge1@2x.png ScrImg_DashboardBadge1@2x.png
cp ./Dashboard-Main/ScrImg_DashboardBadge2.png ScrImg_DashboardBadge2.png
cp ./Dashboard-Main/ScrImg_DashboardBadge2@2x.png ScrImg_DashboardBadge2@2x.png
cp ./Dashboard-Main/ScrImg_DashboardProfileArrow.png ScrImg_DashboardProfileArrow.png
cp ./Dashboard-Main/ScrImg_DashboardProfileArrow@2x.png ScrImg_DashboardProfileArrow@2x.png
cp ./Dashboard-Main/ScrImg_DashboardProfileDash.png ScrImg_DashboardProfileDash.png
cp ./Dashboard-Main/ScrImg_DashboardProfileDash@2x.png ScrImg_DashboardProfileDash@2x.png
cp ./Dashboard-Main/ScrImg_DashLine.png ScrImg_DashLine.png
cp ./Dashboard-Main/ScrImg_DashLine@2x.png ScrImg_DashLine@2x.png
cp ./Dashboard-Main/ScrImg_FacebookConnect.png ScrImg_FacebookConnect.png
cp ./Dashboard-Main/ScrImg_FacebookConnect@2x.png ScrImg_FacebookConnect@2x.png
cp ./Dashboard-Main/ScrImg_FacebookConnectPressed.png ScrImg_FacebookConnectPressed.png
cp ./Dashboard-Main/ScrImg_FacebookConnectPressed@2x.png ScrImg_FacebookConnectPressed@2x.png
cp ./Dashboard-Main/ScrImg_FeedbackIcon.png ScrImg_FeedbackIcon.png
cp ./Dashboard-Main/ScrImg_FeedbackIcon@2x.png ScrImg_FeedbackIcon@2x.png
cp ./Dashboard-Main/ScrImg_FindInviteIcon.png ScrImg_FindInviteIcon.png
cp ./Dashboard-Main/ScrImg_FindInviteIcon@2x.png ScrImg_FindInviteIcon@2x.png
cp ./Dashboard-Main/ScrImg_MessagesIcon.png ScrImg_MessagesIcon.png
cp ./Dashboard-Main/ScrImg_MessagesIcon@2x.png ScrImg_MessagesIcon@2x.png
cp ./Dashboard-Main/ScrImg_PoweredByFoot.png ScrImg_PoweredByFoot.png
cp ./Dashboard-Main/ScrImg_PoweredByFoot@2x.png ScrImg_PoweredByFoot@2x.png
cp ./Dashboard-Main/ScrImg_PoweredByScringo.png ScrImg_PoweredByScringo.png
cp ./Dashboard-Main/ScrImg_PoweredByScringo@2x.png ScrImg_PoweredByScringo@2x.png
cp ./Dashboard-Main/ScrImg_ProfileOverlay.png ScrImg_ProfileOverlay.png
cp ./Dashboard-Main/ScrImg_ProfileOverlay@2x.png ScrImg_ProfileOverlay@2x.png
cp ./Dashboard-Main/ScrImg_ProfileShade.png ScrImg_ProfileShade.png
cp ./Dashboard-Main/ScrImg_ProfileShade@2x.png ScrImg_ProfileShade@2x.png
cp ./Dashboard-Main/ScrImg_ProfileThumbBig.png ScrImg_ProfileThumbBig.png
cp ./Dashboard-Main/ScrImg_ProfileThumbBig@2x.png ScrImg_ProfileThumbBig@2x.png
cp ./Dashboard-Main/ScrImg_RadarIcon.png ScrImg_RadarIcon.png
cp ./Dashboard-Main/ScrImg_RadarIcon@2x.png ScrImg_RadarIcon@2x.png
cp ./Dashboard-Main/ScrImg_TwitterConnect.png ScrImg_TwitterConnect.png
cp ./Dashboard-Main/ScrImg_TwitterConnect@2x.png ScrImg_TwitterConnect@2x.png
cp ./Dashboard-Main/ScrImg_TwitterConnectPressed.png ScrImg_TwitterConnectPressed.png
cp ./Dashboard-Main/ScrImg_TwitterConnectPressed@2x.png ScrImg_TwitterConnectPressed@2x.png
cp ./Default-Elements/ScrImg_BackArrow.png ScrImg_BackArrow.png
cp ./Default-Elements/ScrImg_BackArrow@2x.png ScrImg_BackArrow@2x.png
cp ./Default-Elements/ScrImg_BackBtn.png ScrImg_BackBtn.png
cp ./Default-Elements/ScrImg_BackBtn@2x.png ScrImg_BackBtn@2x.png
cp ./Default-Elements/ScrImg_BackBtnPressed.png ScrImg_BackBtnPressed.png
cp ./Default-Elements/ScrImg_BackBtnPressed@2x.png ScrImg_BackBtnPressed@2x.png
cp ./Default-Elements/ScrImg_BackRibbon.png ScrImg_BackRibbon.png
cp ./Default-Elements/ScrImg_BackRibbon@2x.png ScrImg_BackRibbon@2x.png
cp ./Default-Elements/ScrImg_DefaultBlueBtn.png ScrImg_DefaultBlueBtn.png
cp ./Default-Elements/ScrImg_DefaultBlueBtn@2x.png ScrImg_DefaultBlueBtn@2x.png
cp ./Default-Elements/ScrImg_DefaultBlueBtnPressed.png ScrImg_DefaultBlueBtnPressed.png
cp ./Default-Elements/ScrImg_DefaultBlueBtnPressed@2x.png ScrImg_DefaultBlueBtnPressed@2x.png
cp ./Default-Elements/ScrImg_DefaultGreyBtn.png ScrImg_DefaultGreyBtn.png
cp ./Default-Elements/ScrImg_DefaultGreyBtn2.png ScrImg_DefaultGreyBtn2.png
cp ./Default-Elements/ScrImg_DefaultGreyBtn2@2x.png ScrImg_DefaultGreyBtn2@2x.png
cp ./Default-Elements/ScrImg_DefaultGreyBtn2Pressed.png ScrImg_DefaultGreyBtn2Pressed.png
cp ./Default-Elements/ScrImg_DefaultGreyBtn2Pressed@2x.png ScrImg_DefaultGreyBtn2Pressed@2x.png
cp ./Default-Elements/ScrImg_DefaultGreyBtn@2x.png ScrImg_DefaultGreyBtn@2x.png
cp ./Default-Elements/ScrImg_DefaultGreyBtnPressed.png ScrImg_DefaultGreyBtnPressed.png
cp ./Default-Elements/ScrImg_DefaultGreyBtnPressed@2x.png ScrImg_DefaultGreyBtnPressed@2x.png
cp ./Default-Elements/ScrImg_DefaultGreyBtnSmall.png ScrImg_DefaultGreyBtnSmall.png
cp ./Default-Elements/ScrImg_DefaultGreyBtnSmall@2x.png ScrImg_DefaultGreyBtnSmall@2x.png
cp ./Default-Elements/ScrImg_DefaultGreyBtnSmallPressed.png ScrImg_DefaultGreyBtnSmallPressed.png
cp ./Default-Elements/ScrImg_DefaultGreyBtnSmallPressed@2x.png ScrImg_DefaultGreyBtnSmallPressed@2x.png
cp ./Default-Elements/ScrImg_DefaultPopupBg.png ScrImg_DefaultPopupBg.png
cp ./Default-Elements/ScrImg_DefaultPopupBg@2x.png ScrImg_DefaultPopupBg@2x.png
cp ./Default-Elements/ScrImg_DefaultWhiteCell.png ScrImg_DefaultWhiteCell.png
cp ./Default-Elements/ScrImg_DefaultWhiteCell@2x.png ScrImg_DefaultWhiteCell@2x.png
cp ./Default-Elements/ScrImg_MainIcon.png ScrImg_MainIcon.png
cp ./Default-Elements/ScrImg_MainIcon@2x.png ScrImg_MainIcon@2x.png
cp ./Default-Elements/ScrImg_NavBar.png ScrImg_NavBar.png
cp ./Default-Elements/ScrImg_NavBar@2x.png ScrImg_NavBar@2x.png
cp ./Default-Elements/ScrImg_SearchBg.png ScrImg_SearchBg.png
cp ./Default-Elements/ScrImg_SearchBg@2x.png ScrImg_SearchBg@2x.png
cp ./Default-Elements/ScrImg_SearchIcon.png ScrImg_SearchIcon.png
cp ./Default-Elements/ScrImg_SearchIcon@2x.png ScrImg_SearchIcon@2x.png
cp ./Feedback/ScrImg_AppFeedbackIcon.png ScrImg_AppFeedbackIcon.png
cp ./Feedback/ScrImg_AppFeedbackIcon@2x.png ScrImg_AppFeedbackIcon@2x.png
cp ./Feedback/ScrImg_BugIcon.png ScrImg_BugIcon.png
cp ./Feedback/ScrImg_BugIcon@2x.png ScrImg_BugIcon@2x.png
cp ./Feedback/ScrImg_BugIconPressed.png ScrImg_BugIconPressed.png
cp ./Feedback/ScrImg_BugIconPressed@2x.png ScrImg_BugIconPressed@2x.png
cp ./Feedback/ScrImg_FeatureIcon.png ScrImg_FeatureIcon.png
cp ./Feedback/ScrImg_FeatureIcon@2x.png ScrImg_FeatureIcon@2x.png
cp ./Feedback/ScrImg_FeatureIconPressed.png ScrImg_FeatureIconPressed.png
cp ./Feedback/ScrImg_FeatureIconPressed@2x.png ScrImg_FeatureIconPressed@2x.png
cp ./Feedback/ScrImg_FeedbackHead.png ScrImg_FeedbackHead.png
cp ./Feedback/ScrImg_FeedbackHead@2x.png ScrImg_FeedbackHead@2x.png
cp ./Feedback/ScrImg_FeedbackHeadArrow.png ScrImg_FeedbackHeadArrow.png
cp ./Feedback/ScrImg_FeedbackHeadArrow@2x.png ScrImg_FeedbackHeadArrow@2x.png
cp ./Feedback/ScrImg_FeedbackRateIcon.png ScrImg_FeedbackRateIcon.png
cp ./Feedback/ScrImg_FeedbackRateIcon@2x.png ScrImg_FeedbackRateIcon@2x.png
cp ./Feedback/ScrImg_FeedbackUserInfoBg.png ScrImg_FeedbackUserInfoBg.png
cp ./Feedback/ScrImg_FeedbackUserInfoBg@2x.png ScrImg_FeedbackUserInfoBg@2x.png
cp ./Feedback/ScrImg_RatePurpleBtn.png ScrImg_RatePurpleBtn.png
cp ./Feedback/ScrImg_RatePurpleBtn@2x.png ScrImg_RatePurpleBtn@2x.png
cp ./Feedback/ScrImg_RatePurpleBtnPressed.png ScrImg_RatePurpleBtnPressed.png
cp ./Feedback/ScrImg_RatePurpleBtnPressed@2x.png ScrImg_RatePurpleBtnPressed@2x.png
cp ./Feedback/ScrImg_RateStarOff.png ScrImg_RateStarOff.png
cp ./Feedback/ScrImg_RateStarOff@2x.png ScrImg_RateStarOff@2x.png
cp ./Feedback/ScrImg_RateStarOn.png ScrImg_RateStarOn.png
cp ./Feedback/ScrImg_RateStarOn@2x.png ScrImg_RateStarOn@2x.png
cp ./Feedback/ScrImg_RateUsIcon.png ScrImg_RateUsIcon.png
cp ./Feedback/ScrImg_RateUsIcon@2x.png ScrImg_RateUsIcon@2x.png
cp ./Feedback/ScrImg_SendFeedbackIcon.png ScrImg_SendFeedbackIcon.png
cp ./Feedback/ScrImg_SendFeedbackIcon@2x.png ScrImg_SendFeedbackIcon@2x.png
cp ./Feedback/ScrImg_SendFeedbackIconPressed.png ScrImg_SendFeedbackIconPressed.png
cp ./Feedback/ScrImg_SendFeedbackIconPressed@2x.png ScrImg_SendFeedbackIconPressed@2x.png
cp ./Find-Invite/ScrImg_ContactsConnectSmall.png ScrImg_ContactsConnectSmall.png
cp ./Find-Invite/ScrImg_ContactsConnectSmall@2x.png ScrImg_ContactsConnectSmall@2x.png
cp ./Find-Invite/ScrImg_ContactsConnectSmallPressed.png ScrImg_ContactsConnectSmallPressed.png
cp ./Find-Invite/ScrImg_ContactsConnectSmallPressed@2x.png ScrImg_ContactsConnectSmallPressed@2x.png
cp ./Find-Invite/ScrImg_ContactsIcon.png ScrImg_ContactsIcon.png
cp ./Find-Invite/ScrImg_ContactsIcon@2x.png ScrImg_ContactsIcon@2x.png
cp ./Find-Invite/ScrImg_ContactsShadeIcon.png ScrImg_ContactsShadeIcon.png
cp ./Find-Invite/ScrImg_ContactsShadeIcon@2x.png ScrImg_ContactsShadeIcon@2x.png
cp ./Find-Invite/ScrImg_FacebookConnectSmall.png ScrImg_FacebookConnectSmall.png
cp ./Find-Invite/ScrImg_FacebookConnectSmall@2x.png ScrImg_FacebookConnectSmall@2x.png
cp ./Find-Invite/ScrImg_FacebookConnectSmallPressed.png ScrImg_FacebookConnectSmallPressed.png
cp ./Find-Invite/ScrImg_FacebookConnectSmallPressed@2x.png ScrImg_FacebookConnectSmallPressed@2x.png
cp ./Find-Invite/ScrImg_FacebookIcon.png ScrImg_FacebookIcon.png
cp ./Find-Invite/ScrImg_FacebookIcon@2x.png ScrImg_FacebookIcon@2x.png
cp ./Find-Invite/ScrImg_FindBarBg.png ScrImg_FindBarBg.png
cp ./Find-Invite/ScrImg_FindBarBg@2x.png ScrImg_FindBarBg@2x.png
cp ./Find-Invite/ScrImg_FindFriendsIcon.png ScrImg_FindFriendsIcon.png
cp ./Find-Invite/ScrImg_FindFriendsIcon@2x.png ScrImg_FindFriendsIcon@2x.png
cp ./Find-Invite/ScrImg_SuggestionsIcon.png ScrImg_SuggestionsIcon.png
cp ./Find-Invite/ScrImg_SuggestionsIcon@2x.png ScrImg_SuggestionsIcon@2x.png
cp ./Find-Invite/ScrImg_TwitterConnectSmall.png ScrImg_TwitterConnectSmall.png
cp ./Find-Invite/ScrImg_TwitterConnectSmall@2x.png ScrImg_TwitterConnectSmall@2x.png
cp ./Find-Invite/ScrImg_TwitterConnectSmallPressed.png ScrImg_TwitterConnectSmallPressed.png
cp ./Find-Invite/ScrImg_TwitterConnectSmallPressed@2x.png ScrImg_TwitterConnectSmallPressed@2x.png
cp ./Find-Invite/ScrImg_TwitterIcon.png ScrImg_TwitterIcon.png
cp ./Find-Invite/ScrImg_TwitterIcon@2x.png ScrImg_TwitterIcon@2x.png
cp ./FontStyles/ScrImg_01.png ScrImg_01.png
cp ./FontStyles/ScrImg_02.png ScrImg_02.png
cp ./FontStyles/ScrImg_03.png ScrImg_03.png
cp ./FontStyles/ScrImg_04.png ScrImg_04.png
cp ./FontStyles/ScrImg_05.png ScrImg_05.png
cp ./FontStyles/ScrImg_06.png ScrImg_06.png
cp ./FontStyles/ScrImg_07.png ScrImg_07.png
cp ./FontStyles/ScrImg_08.png ScrImg_08.png
cp ./FontStyles/ScrImg_09.png ScrImg_09.png
cp ./FontStyles/ScrImg_10.png ScrImg_10.png
cp ./FontStyles/ScrImg_11.png ScrImg_11.png
cp ./FontStyles/ScrImg_12.png ScrImg_12.png
cp ./FontStyles/ScrImg_13.png ScrImg_13.png
cp ./FontStyles/ScrImg_14.png ScrImg_14.png
cp ./FontStyles/ScrImg_15.png ScrImg_15.png
cp ./FontStyles/ScrImg_16.png ScrImg_16.png
cp ./FontStyles/ScrImg_17.png ScrImg_17.png
cp ./Messages/ScrImg_AppMessageBg.png ScrImg_AppMessageBg.png
cp ./Messages/ScrImg_AppMessageBg@2x.png ScrImg_AppMessageBg@2x.png
cp ./Messages/ScrImg_DelBtn.png ScrImg_DelBtn.png
cp ./Messages/ScrImg_DelBtn@2x.png ScrImg_DelBtn@2x.png
cp ./Messages/ScrImg_DelBtnPressed.png ScrImg_DelBtnPressed.png
cp ./Messages/ScrImg_DelBtnPressed@2x.png ScrImg_DelBtnPressed@2x.png
cp ./Messages/ScrImg_InMessageDash.png ScrImg_InMessageDash.png
cp ./Messages/ScrImg_InMessageDash@2x.png ScrImg_InMessageDash@2x.png
cp ./Messages/ScrImg_InMessageTextField.png ScrImg_InMessageTextField.png
cp ./Messages/ScrImg_InMessageTextField@2x.png ScrImg_InMessageTextField@2x.png
cp ./Messages/ScrImg_InMessageTextFieldBg.png ScrImg_InMessageTextFieldBg.png
cp ./Messages/ScrImg_InMessageTextFieldBg@2x.png ScrImg_InMessageTextFieldBg@2x.png
cp ./Messages/ScrImg_InMessageTextFieldBtn.png ScrImg_InMessageTextFieldBtn.png
cp ./Messages/ScrImg_InMessageTextFieldBtn@2x.png ScrImg_InMessageTextFieldBtn@2x.png
cp ./Messages/ScrImg_InMessageTextFieldBtnPressed.png ScrImg_InMessageTextFieldBtnPressed.png
cp ./Messages/ScrImg_InMessageTextFieldBtnPressed@2x.png ScrImg_InMessageTextFieldBtnPressed@2x.png
cp ./Messages/ScrImg_MessageBubbleMe.png ScrImg_MessageBubbleMe.png
cp ./Messages/ScrImg_MessageBubbleMe@2x.png ScrImg_MessageBubbleMe@2x.png
cp ./Messages/ScrImg_MessageBubbleUser.png ScrImg_MessageBubbleUser.png
cp ./Messages/ScrImg_MessageBubbleUser@2x.png ScrImg_MessageBubbleUser@2x.png
cp ./Messages/ScrImg_NewMessagesIcon.png ScrImg_NewMessagesIcon.png
cp ./Messages/ScrImg_NewMessagesIcon@2x.png ScrImg_NewMessagesIcon@2x.png
cp ./Messages/ScrImg_NoMessagesArrow.png ScrImg_NoMessagesArrow.png
cp ./Messages/ScrImg_NoMessagesArrow@2x.png ScrImg_NoMessagesArrow@2x.png
cp ./Messages/ScrImg_NoMessagesIcon.png ScrImg_NoMessagesIcon.png
cp ./Messages/ScrImg_NoMessagesIcon@2x.png ScrImg_NoMessagesIcon@2x.png
cp ./Messages/ScrImg_PopupMsgBg.png ScrImg_PopupMsgBg.png
cp ./Messages/ScrImg_PopupMsgBg@2x.png ScrImg_PopupMsgBg@2x.png
cp ./Messages/ScrImg_PopupMsgClose.png ScrImg_PopupMsgClose.png
cp ./Messages/ScrImg_PopupMsgClose@2x.png ScrImg_PopupMsgClose@2x.png
cp ./Messages/ScrImg_RefreshIcon.png ScrImg_RefreshIcon.png
cp ./Messages/ScrImg_RefreshIcon@2x.png ScrImg_RefreshIcon@2x.png
cp ./Messages/ScrImg_SectionDash.png ScrImg_SectionDash.png
cp ./Messages/ScrImg_SectionDash@2x.png ScrImg_SectionDash@2x.png
cp ./Messages/ScrImg_UserThumbMedium.png ScrImg_UserThumbMedium.png
cp ./Messages/ScrImg_UserThumbMedium@2x.png ScrImg_UserThumbMedium@2x.png
cp ./Messages/ScrImg_UserThumbMediumNon.png ScrImg_UserThumbMediumNon.png
cp ./Messages/ScrImg_UserThumbMediumNon@2x.png ScrImg_UserThumbMediumNon@2x.png
cp ./Messages/ScrImg_UserThumbSmall.png ScrImg_UserThumbSmall.png
cp ./Messages/ScrImg_UserThumbSmall@2x.png ScrImg_UserThumbSmall@2x.png
cp ./Messages/ScrImg_WriteCell.png ScrImg_WriteCell.png
cp ./Messages/ScrImg_WriteCell@2x.png ScrImg_WriteCell@2x.png
cp ./MyProfile/ScrImg_EditIcon.png ScrImg_EditIcon.png
cp ./MyProfile/ScrImg_EditIcon@2x.png ScrImg_EditIcon@2x.png
cp ./MyProfile/ScrImg_FacebookBigConnect.png ScrImg_FacebookBigConnect.png
cp ./MyProfile/ScrImg_FacebookBigConnect@2x.png ScrImg_FacebookBigConnect@2x.png
cp ./MyProfile/ScrImg_FacebookBigConnectPressed.png ScrImg_FacebookBigConnectPressed.png
cp ./MyProfile/ScrImg_FacebookBigConnectPressed@2x.png ScrImg_FacebookBigConnectPressed@2x.png
cp ./MyProfile/ScrImg_FacebookShadeIcon.png ScrImg_FacebookShadeIcon.png
cp ./MyProfile/ScrImg_FacebookShadeIcon@2x.png ScrImg_FacebookShadeIcon@2x.png
cp ./MyProfile/ScrImg_ProfileCell.png ScrImg_ProfileCell.png
cp ./MyProfile/ScrImg_ProfileCell@2x.png ScrImg_ProfileCell@2x.png
cp ./MyProfile/ScrImg_TwitterBigConnect.png ScrImg_TwitterBigConnect.png
cp ./MyProfile/ScrImg_TwitterBigConnect@2x.png ScrImg_TwitterBigConnect@2x.png
cp ./MyProfile/ScrImg_TwitterBigConnectPressed.png ScrImg_TwitterBigConnectPressed.png
cp ./MyProfile/ScrImg_TwitterBigConnectPressed@2x.png ScrImg_TwitterBigConnectPressed@2x.png
cp ./MyProfile/ScrImg_TwitterShadeIcon.png ScrImg_TwitterShadeIcon.png
cp ./MyProfile/ScrImg_TwitterShadeIcon@2x.png ScrImg_TwitterShadeIcon@2x.png
cp ./Profile/ScrImg_NotificationBg.png ScrImg_NotificationBg.png
cp ./Profile/ScrImg_NotificationBg@2x.png ScrImg_NotificationBg@2x.png
cp ./Profile/ScrImg_NotificationCheck.png ScrImg_NotificationCheck.png
cp ./Profile/ScrImg_NotificationCheck@2x.png ScrImg_NotificationCheck@2x.png
cp ./Profile/ScrImg_UserMessageIcon.png ScrImg_UserMessageIcon.png
cp ./Profile/ScrImg_UserMessageIcon@2x.png ScrImg_UserMessageIcon@2x.png
cp ./Profile/ScrImg_UserMidBar.png ScrImg_UserMidBar.png
cp ./Profile/ScrImg_UserMidBar@2x.png ScrImg_UserMidBar@2x.png
cp ./Profile/ScrImg_UserMidBarBottomShade.png ScrImg_UserMidBarBottomShade.png
cp ./Profile/ScrImg_UserMidBarBottomShade@2x.png ScrImg_UserMidBarBottomShade@2x.png
cp ./Profile/ScrImg_UserMoreIcon.png ScrImg_UserMoreIcon.png
cp ./Profile/ScrImg_UserMoreIcon@2x.png ScrImg_UserMoreIcon@2x.png
cp ./Radar/ScrImg_ListIcon.png ScrImg_ListIcon.png
cp ./Radar/ScrImg_ListIcon@2x.png ScrImg_ListIcon@2x.png
cp ./Radar/ScrImg_LocateMeBtn.png ScrImg_LocateMeBtn.png
cp ./Radar/ScrImg_LocateMeBtn@2x.png ScrImg_LocateMeBtn@2x.png
cp ./Radar/ScrImg_LocateMeBtnPressed.png ScrImg_LocateMeBtnPressed.png
cp ./Radar/ScrImg_LocateMeBtnPressed@2x.png ScrImg_LocateMeBtnPressed@2x.png
cp ./Radar/ScrImg_MapIcon.png ScrImg_MapIcon.png
cp ./Radar/ScrImg_MapIcon@2x.png ScrImg_MapIcon@2x.png
cp ./Radar/ScrImg_NewFollowersShadeInvert.png ScrImg_NewFollowersShadeInvert.png
cp ./Radar/ScrImg_NewFollowersShadeInvert@2x.png ScrImg_NewFollowersShadeInvert@2x.png
cp ./Radar/ScrImg_NotNowBtn@2X.png ScrImg_NotNowBtn@2X.png
cp ./Radar/ScrImg_OffUserRadarBg.png ScrImg_OffUserRadarBg.png
cp ./Radar/ScrImg_OffUserRadarBg@2x.png ScrImg_OffUserRadarBg@2x.png
cp ./Radar/ScrImg_RadarUserNotSignedIcon.png ScrImg_RadarUserNotSignedIcon.png
cp ./Radar/ScrImg_RadarUserNotSignedIcon@2x.png ScrImg_RadarUserNotSignedIcon@2x.png
cp ./Radar/ScrImg_UpperShade.png ScrImg_UpperShade.png
cp ./Radar/ScrImg_UpperShade@2x.png ScrImg_UpperShade@2x.png
cp ./Radar/ScrImg_UserRadarBg.png ScrImg_UserRadarBg.png
cp ./Radar/ScrImg_UserRadarBg@2x.png ScrImg_UserRadarBg@2x.png
